console.log(isNaN("100")); // false
console.log(isNaN(100)); // false
console.log(isNaN("abc")); // ture
console.log(isNaN(true)); // false
console.log(isNaN(false)); // false
console.log(isNaN(undefined)); // true
console.log(isNaN(null)); // false
console.log(isNaN(Infinity)); // false
console.log(isNaN(NaN)); // true
